# Generated by Django 5.2.4 on 2025-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="notes",
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
